# RANDOM.RANDINT()
# Gera números inteiros aleatórios em um intervalo definido
#random.randint(1, 10)


# RANDOM.SHUFFLE()
# Embaralha os elementos de uma lista no local
# random.shuffle(lista)

# RANDOM.CHOICE()
# Escolhe um elemento aleatório de uma lista
# random.choice(['A', 'B', 'C'])

# RANDOM.RANDOM()
# Retorna número decimal entre 0.0 e 1.0
# random.random()




# DADO VIRTUAL
# import random
# dado = random.randint(1, 97)
# print(f"Você tirou: {dado}")

# MOEDA
# import random
# moeda = random.choice(['Cara🤡', 'Coroa👑'])
# print(f"Resultado: {moeda}")

#ALUNOS
# import random
# ALUNOS = ['Ana😎', 'Bruno😒', 'Carlos😒', 'Diana😎', 'Eduardo😒']
# sorteado = random.choice(ALUNOS)
# print(f"o aluno sorteado foi: {sorteado}")



#ADVINHE O NÚMERO
# import random
# numero = random.randint(1, 50)
# print("Bem vindo ao jogo de advinhe o número!")

# while True:
#     chute = int(input("Digite um número entre 1 e 50: "))
#     if chute < numero:
#         print("Tente um número maior!")
#     else:
#         print("Tente um número menor!")
#     if chute == numero:
#         print("Parabéns! Você acertou!")
#         break






